### ISSUE TITLE
User Submissions?

### ISSUE THREAD

**Issue by LAX18** [deadphoenix8091/tinydb#6]
Just curious as to whether users will be able to add to the db, seeing as that feature was abused and lead to the downfall of the original TitlesDB.

**Comment by deadphoenix8091** [comment]
From the Rules&Guidelines on tinydb: 
"OR if you are not related to the project, you believe in good faith that the project team will or would give permission for the project to be linked on TinyDB (the project team may be contacted for this purpose)"

Yes user submissions are okay, we check each submission beforehand. A rich featured Moderation GUI for this is in the works. Automatic release scanning and metadata extraction from cia files also helps in deciding weither or not an application can be approved to tinydb.

Since tinydb works by monitoring github projects instead of direct cia uploads we have a much better way of getting official releases only. Forks or fake applications can be caught in the submission process.

Piracy would also need to be uploaded through github which is an additional barrier for abuse. (While it probably wont stop people from trying it, we have a much better way of catching them now)


Sorry for rambling, writing this on the go. Hope I got the point across in an understandable way.

**Comment by LAX18** [comment]
Ah okay. Just fear that a complex process may prevent submissions
